# -*- coding: utf-8 -*-
"""placement_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3AjUf_AqQQlGmlY9flVotS276xJCdUx
"""

!pip install -q -U langchain langchain-google-genai pypdf ddgs google-genai

import sys
if 'google.colab' in sys.modules:
  !pip install google-auth==2.49.0

import os
import getpass

os.environ["GOOGLE_API_KEY"] = getpass.getpass(
    "Enter your Gemini API key: "
)

print("API key loaded:", bool(os.environ.get("GOOGLE_API_KEY")))

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemma-4-31b-it",
    temperature=0.2,
    max_retries=2
)

response = llm.invoke(
    "Explain what an AI agent is in one simple sentence."
)

print(response.text)

from google.colab import files

uploaded = files.upload()

pdf_files = [
    name for name in uploaded.keys()
    if name.lower().endswith(".pdf")
]

if not pdf_files:
    raise ValueError("Please upload a PDF resume.")

RESUME_PATH = pdf_files[0]

print("Resume uploaded:", RESUME_PATH)

ROLE = input("Enter the job role you want: ").strip()

GITHUB_ID = input(
    "Enter your GitHub username or GitHub URL: "
).strip()

print("Role:", ROLE)
print("GitHub:", GITHUB_ID)

import langchain
import langchain_google_genai
import google.genai
import requests

print("LangChain:", langchain.__version__)
print("Requests:", requests.__version__)
print("Packages installed successfully")

import os
import getpass

api_key = getpass.getpass("Paste your NEW Gemini API key: ")

os.environ["GEMINI_API_KEY"] = api_key
os.environ["GOOGLE_API_KEY"] = api_key

print("API key loaded:", bool(api_key))
print("Key length:", len(api_key))

from google import genai

client = genai.Client(
    api_key=api_key
)

response = client.models.generate_content(
    model="gemma-4-31b-it",
    contents="Say hello in one short sentence."
)

print(response.text)

api_key = getpass.getpass("Paste your NEW Gemini API key: ")

os.environ["GEMINI_API_KEY"] = api_key
os.environ["GOOGLE_API_KEY"] = api_key

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemma-4-31b-it",
    temperature=0.2,
    max_retries=2
)

response = llm.invoke(
    "Explain AI agent in one simple sentence."
)

print(response.text)

from google.colab import files

uploaded = files.upload()

pdf_files = [
    name for name in uploaded.keys()
    if name.lower().endswith(".pdf")
]

if not pdf_files:
    raise ValueError("Please upload a PDF resume.")

RESUME_PATH = pdf_files[0]

print("Resume:", RESUME_PATH)

tools = [
    read_resume,
    job_search,
    skill_gap,
    project_ideas,
    github_check
]

tool_map = {
    tool.name: tool
    for tool in tools
}

print("Tools available to the agent:")
for tool in tools:
    print("-", tool.name)

"""## Create the LangChain Agent
Now, let's create our LangChain agent. This agent will be able to use the tools we've just defined to help students with their career journey. We'll use a `create_tool_calling_agent` for this.
"""

ROLE = input("Enter target job role: ").strip()

GITHUB_ID = input(
    "Enter GitHub username or GitHub URL: "
).strip()

print()
print("Target Role:", ROLE)
print("GitHub:", GITHUB_ID)

"""## Invoke the Agent
Finally, let's invoke our agent with a query to start assisting the student. The agent will use its available tools to answer the query.
"""

import json
import requests

from pypdf import PdfReader
from ddgs import DDGS

from langchain_core.tools import tool

print("Imports successful")

@tool
def read_resume() -> str:
    """Read and extract text from the student's resume PDF."""

    reader = PdfReader(RESUME_PATH)

    text = ""

    for page in reader.pages:
        text += (page.extract_text() or "") + "\n"

    text = text.strip()

    if not text:
        return "No readable text found in the resume PDF."

    return text[:16000]

resume_text = read_resume.invoke({})

print(resume_text[:3000])

@tool
def job_search(role: str) -> str:
    """Search for jobs related to the target role."""

    query = f"{role} jobs India fresher entry level"

    try:
        results = DDGS().text(
            query,
            max_results=5
        )

        output = []

        for item in results:
            output.append({
                "title": item.get("title", ""),
                "url": item.get("href", ""),
                "snippet": item.get("body", "")
            })

        return json.dumps(output, indent=2)

    except Exception as e:
        return f"Job search failed: {e}"

print(job_search.invoke({
    "role": ROLE
}))

@tool
def skill_gap(role: str, resume_text: str) -> str:
    """Compare resume skills with the target job role."""

    prompt = f"""
You are a career skill gap analyzer.

Target role:
{role}

Resume:
{resume_text}

Compare the student's current skills with the target role.

Give:

1. Matching skills
2. Missing skills
3. Technologies to learn
4. Priority of each skill
5. Simple learning plan

Keep it suitable for a college student.
"""

    response = llm.invoke(prompt)

    return response.text

print(
    skill_gap.invoke({
        "role": ROLE,
        "resume_text": resume_text
    })
)

@tool
def project_ideas(role: str) -> str:
    """Search for student project ideas related to the target role."""

    query = f"{role} student project ideas GitHub"

    try:
        results = DDGS().text(
            query,
            max_results=5
        )

        output = []

        for item in results:
            output.append({
                "title": item.get("title", ""),
                "url": item.get("href", ""),
                "snippet": item.get("body", "")
            })

        return json.dumps(output, indent=2)

    except Exception as e:
        return f"Project search failed: {e}"

@tool
def github_check(github_id: str) -> str:
    """Check public GitHub repository activity."""

    username = github_id.strip().rstrip("/").split("/")[-1]

    url = f"https://api.github.com/users/{username}/repos"

    try:
        response = requests.get(
            url,
            params={
                "sort": "pushed",
                "direction": "desc",
                "per_page": 10
            },
            timeout=20
        )

        if response.status_code == 404:
            return f"GitHub user '{username}' not found."

        response.raise_for_status()

        repos = response.json()

        result = {
            "username": username,
            "repositories": []
        }

        for repo in repos:
            result["repositories"].append({
                "name": repo.get("name"),
                "description": repo.get("description"),
                "language": repo.get("language"),
                "stars": repo.get("stargazers_count"),
                "url": repo.get("html_url"),
                "last_pushed": repo.get("pushed_at")
            })

        return json.dumps(result, indent=2)

    except Exception as e:
        return f"GitHub check failed: {e}"

tools = [
    read_resume,
    job_search,
    skill_gap,
    project_ideas,
    github_check
]

for t in tools:
    print(t.name)

agent_llm = llm.bind_tools(tools)

print("Agent core created successfully.")

from langchain_core.messages import (
    HumanMessage,
    SystemMessage
)

SYSTEM_PROMPT = """
You are a Student Career Agent.

Your job is to analyze a student's resume
and target career role.

Available tools:

- read_resume
- job_search
- skill_gap
- project_ideas
- github_check

Process:

1. Read the resume.
2. Analyze skill gaps.
3. Search relevant jobs.
4. Find useful project ideas.
5. Check GitHub activity.
6. Combine all results.
7. Give a final career recommendation.

You can call tools when needed.

Do not invent information.

Final response should contain:

- Resume summary
- Target role
- Matching skills
- Skill gaps
- Jobs
- Project ideas
- GitHub activity
- Recommended next steps
"""

messages = [
    SystemMessage(content=SYSTEM_PROMPT),

    HumanMessage(
        content=f"""
Analyze this student's career profile.

Target role:
{ROLE}

GitHub:
{GITHUB_ID}

The resume is available through the read_resume tool.
"""
    )
]

tool_map = {
    t.name: t
    for t in tools
}

trace = []

for step in range(10):

    print("\n" + "=" * 60)
    print("AGENT STEP", step + 1)
    print("=" * 60)

    response = agent_llm.invoke(messages)

    messages.append(response)

    # Agent finished
    if not response.tool_calls:
        print("\nFINAL ANSWER\n")
        print(response.text)
        final_answer = response.text
        break

    # Agent selected tools
    for call in response.tool_calls:

        tool_name = call["name"]
        tool_args = call["args"]

        print("\nTOOL SELECTED:", tool_name)
        print("ARGUMENTS:", tool_args)

        trace.append({
            "step": step + 1,
            "tool": tool_name,
            "arguments": tool_args
        })

        selected_tool = tool_map[tool_name]

        result = selected_tool.invoke(call)

        messages.append(result)

        print("TOOL COMPLETED")

result = {
    "student_input": {
        "resume": RESUME_PATH,
        "role": ROLE,
        "github": GITHUB_ID
    },

    "model": "gemma-4-31b-it",

    "tool_trace": trace,

    "final_synthesis": final_answer
}

print(
    json.dumps(
        result,
        indent=2,
        ensure_ascii=False
    )
)

